### ISSUE TITLE
Ditch Babel

### ISSUE THREAD

**Issue by sarendipitee** [jh3y/bolt#9]
Can we ditch Babel? Node supports all the ES6 stuff out of the box now and it's really wonky to me to be maintaining/committing two trees in src and lib.

Switch would be easy. Delete current lib/, move everything from src/ to root.

**Comment by jh3y** [comment]
Hey @JonDum 

Thanks for contributing. I haven't touched `russ` much since I put it together and you're right, `node` has moved on some versions now since writing and `ES6` support is much better 👍 

Sounds like a plan!

@jh3y
